version: '3'
services:
  db:
    image: 'postgres:13.7'
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=superstore
    ports:
      - '5433:5432'
      
    volumes:
    - superstore_pg_data:/var/lib/postgresql/data/ 
volumes:
  superstore_pg_data: # named volumes can be managed easier using docker-compose
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL : "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD : "admin"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - db
