
version: '3'
services:
  db:
    image: 'postgres:13.7'
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=superstore
    ports:
      - '5432:5432'
      
    volumes:
    - superstore_pg_data:/var/lib/postgresql/data/ 
  db_mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - DATABASE_HOST=127.0.0.1
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=superstore
    ports:
      - '3306:3306'
      
    volumes:
    - superstore_mysql_data:/var/lib/mysql
volumes:
  superstore_pg_data: # named volumes can be managed easier using docker-compose
  superstore_mysql_data: # named volumes can be managed easier using docker-compose
  
